apiVersion: v1
kind: Namespace
metadata:
  name: landingpage

# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: landingpage-cert
#   namespace: landingpage
# spec:
#   secretName: landingpage-tls-secret
#   issuerRef:
#     name: selfsigned-issuer
#     kind: ClusterIssuer
#   dnsNames:
#     - nejlikka.com
#       www.nejlikka.com
#
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landingpage
  namespace: landingpage
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-le-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    gethomepage.dev/description: Landing page for myself
    gethomepage.dev/name: Landing page
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Deployments
    gethomepage.dev/icon: nginx.png
    gethomepage.dev/pod-selector: app=landingpage
spec:
  ingressClassName: traefik
  rules:
  - host: aboutme.nejlikka.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-landingpage
            port:
              number: 80
  tls:
  - hosts:
    - aboutme.nejlikka.com
    secretName: landingpage-cert

---
apiVersion: v1
kind: Service
metadata:
  name: svc-landingpage
  namespace: landingpage
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: landingpage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landingpage
  namespace: landingpage
spec:
  selector:
    matchLabels:
      app: landingpage
  replicas: 1
  template:
    metadata:
      labels:
        app: landingpage
    spec:
      containers:
      - name: landingpage
        image: pontusc/aboutme:latest
        ports:
        - containerPort: 80
